class Posts {
  String image,
      description,
      date,
      time,
      phnum,
      volname,
      status,
      location,
      categpry,
      sname,
      sphnum,
      key,
      pursuit;
  Posts(
      this.image,
      this.description,
      this.date,
      this.time,
      this.phnum,
      this.volname,
      this.status,
      this.location,
      this.categpry,
      this.sname,
      this.sphnum,
      this.key,
      this.pursuit);
}
